Component/agency form
BluelineInnovations/NG.FE pull request #32
Opened 2021-02-10 21:47 UTC by solidstatejake

Request to merge refined implementation of Agency Form into develop branch.

2021-02-11 03:56 UTC, zhwatts requested changes
Please implement custom error messages for type validation. We should not be returning any information about how we perform pre-flight formatting to the front end. I also don't understand some of the micro abstractions you're doing on the material Grid components.

2021-02-11 03:56 UTC, zhwatts commented on src/components/AgencyForm.js
> +                  formState.errors.relatedMaypopAgencyId &&
These error messages shouldn't be shown on frontend. Suggest simplifying the message. Yup allows .typeError(string) method chaining in the validationScheme shape to define custom error messages if type is violated. 

`state: yup.object().typeError('not an object').required(),`

![image](https://user-images.githubusercontent.com/9981733/107597226-06775280-6be8-11eb-956b-d12e531b9640.png)

2021-02-11 03:56 UTC, zhwatts commented on src/components/AgencyForm.js
> +              errorMessage={formState.errors.address && formState.errors.address.message.replace('address', 'Address')}
Consider a utility that takes the error message returned. One could map through and set errors in a single place, using the form element ref. Another option would be to define custom messages at the validation shape closure.

![image](https://user-images.githubusercontent.com/9981733/107600303-573f7900-6bf1-11eb-84a2-13f8e8cccdc6.png)

2021-02-11 03:56 UTC, zhwatts commented on src/components/AgencyForm.js
> +                  errorMessage={formState.errors.state && formState.errors.state.message.replace('state', 'State')}
See my comment above in the CotrolledAutocomplete, regarding option and onChange value... this is a good example where, the Maypop list should return an id, but the state list should return an object... the ControlledAutoComplete abstraction will not work for both becuase the return property ID is statically defined.

2021-02-11 03:56 UTC, zhwatts commented on src/components/Container.js
> +import React from 'react';
This name is not descriptive. You're returning. grid element, so at the very least call the file GridContainer... i'm not sure why we're abstacting a Material UI component here... there's nothing custom about it.

2021-02-11 03:56 UTC, zhwatts commented on src/components/ContainerItem.js
> +
This name is not descriptive. You're returning. grid element, so at the very least call the file GridContainerItem... i'm not sure why we're abstacting a Material UI component here... there's nothing custom about it.

2021-02-11 03:56 UTC, zhwatts commented on src/components/Item.js
> +
Again... I don't understand these micro abstractions

2021-02-11 14:12 UTC, buihdk commented on src/components/AgencyForm.js
> +const AgencyForm = ({ maypopAgencies }) => {
we should start adding proptypes to cover any props passing from parents. in this case, it's `maypopAgencies`

2021-02-11 15:02 UTC, solidstatejake commented on src/components/Container.js
> +import React from 'react';
It was for the same reason as the abstraction of the Controlled elements: due to the nature of flexbox, the markup becomes very complicated when every element is a <Grid item />, <Grid container />, or <Grid container  item/> as opposed to <Item />,  <Container />, or <ContainerItem />.

2021-02-12 12:25 UTC, buihdk commented on package.json
> +      "react/forbid-prop-types": "off",
is there a reason why we turned this off?

2021-02-12 12:25 UTC, buihdk commented on src/components/AgencyForm.js
> +  maypopAgencies: PropTypes.array.isRequired,
we should try not to use `eslint-disable-next-line` often. This can be fixed by changing it to `PropTypes.arrayOf({})`. More info can be found here https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md

2021-02-12 12:25 UTC, buihdk commented on src/components/forms/ControlledTextField.js
> +  control: PropTypes.object.isRequired,
it can be changed to `PropTypes.shape({})` to avoid the lint. More info can be found here https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md

2021-02-12 12:25 UTC, buihdk commented on src/components/forms/ControlledAutocomplete.js
> +  /* eslint-disable-next-line react/forbid-prop-types */
same as above

2021-02-12 12:25 UTC, buihdk commented on src/components/forms/ControlledAutocomplete.js
> +  /* eslint-disable-next-line react/forbid-prop-types */
we don't need this line here for `bool`

2021-02-12 12:27 UTC, buihdk commented on package.json
> +    "prop-types": "^15.7.2",
CRA comes with PropTypes lib so we don't need to add manually to avoid mismatched versions

2021-02-12 14:09 UTC, solidstatejake commented on package.json
> +      "react/forbid-prop-types": "off",
Yes,  it’s preventing `object` and `array` `PropTypes`. Turning it off didn’t do anything, for some reason.

2021-02-12 14:18 UTC, solidstatejake commented on src/components/forms/ControlledTextField.js
> +  control: PropTypes.object.isRequired,
`control` comes from the `react-hook-form` library, and is pumped directly into a `react-hook-form` `Controller` component. I don’t know how to describe its shape other than ‘object’.

2021-02-13 16:25 UTC, zhwatts commented on src/components/Container.js
> +import React from 'react';
But there's nothing custom about this component. What is there to abstract? You're just filling the component with props.

2021-02-13 16:28 UTC, merged